[package]
name = "chess_burd"
version = "0.1.0"
authors = ["MelonShooter <14815068+MelonShooter@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2.0"
serenity = "0.10.4"